version: '2'
services:
  backend:
    build: ./backend
    working_dir: /var/www/${APP_NAME}
    restart: on-failure
    volumes:
     - ./src/:/var/www/${APP_NAME}/
    command: npm run serve:${NODE_ENV}
    networks:
      corpsite:
        ipv4_address: 172.100.100.20
    extra_hosts:
     - "admin.$SERVER_NAME:172.100.100.40"
#    ports:
#      - 5858:5858

  web-srv:
    build: ./nginx
    depends_on:
     - backend
    ports:
     - ${WEB_SRV_PORT}:80
     - ${WEB_SRV_PORT_SSL}:443
    volumes:
     - ./nginx/configs/conf.d/:/etc/nginx/conf.d/
     - ./nginx/configs/nginx.conf:/etc/nginx/nginx.conf
     - ./nginx/ssl/:/etc/nginx/ssl/
     - ./nginx/configs/.htpasswd:/etc/nginx/.htpasswd
    volumes_from:
     - backend
    environment:
     APP_NAME: ${APP_NAME}
    networks:
      corpsite:
        ipv4_address: 172.100.100.40

networks:
  corpsite:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "true"
    ipam:
      driver: default
      config:
      - subnet: 172.100.100.0/24
        gateway: 172.100.100.1

